---
title: "lab10"
author: "Nick McManus"
date: "11/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(usethis)
library(janitor)

# new packages
library(beepr)
library(praise)
library(cowsay)
library(paletteer)
library(sf)
```


## beepr beeps

Use the function `beep()` in the beepr package to made an audio alert when your code is done running.

```{r, eval = FALSE}
# writing for loop
for (i in rev(seq(1:9999))) {
  
  print(paste(i, "bottles of beer on the wall")) #paste adds space
  
}

beep(5)
```


## praise and cowsay

Packages built with a single purpose: to be kind and fun.

```{r}
praise("${Exclamation}, ${EXCLAMATION} ... ${exclamation}!!!!")

praise("Holy ${creating}, Batman - this code is ${ADJECTIVE}!")
```

Use cowsay::say() to make a character say something to you

```{r}
say("Obey", by = "hypnotoad")
```

## Use paletteer to access thousands of color palettes

```{r}
storms %>% 
  group_by(name) %>% 
  summarize(min_pressure = min(pressure, na.rm = TRUE)) %>% 
  slice_min(n = 10, min_pressure) %>% 
  ggplot(aes(x = min_pressure, y = name)) +
  geom_col(aes(fill = name)) +
  scale_fill_paletteer_d("palettetown::dragonite")
```



